name: Backend Test

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2

      - name: List directory structure
        run: ls -R
        shell: bash
      
      - name: Install dependencies
        run: npm install
        working-directory: ./badmaking_joueurs/backend
  
      - name: Run tests
        run: npm test
        working-directory: ./badmaking_joueurs/backend
