name: frontend

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x] # Specify Node.js versions here

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Change to frontend directory
      run: cd client
    - name: Install dependencies
      run: npm install
    - name: Run Jest tests
      run: npx jest
