name: test react
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd backend
        cd routes
        npm install
    - name: Run tests
      run: |
        cd backend
        cd routes
        npx jest
